#!/usr/bin/env ruby

puts <<EOS
1. Get a developer token from:
  - for sandbox: https://sandbox.evernote.com/api/DeveloperToken.action
  - for production: https://www.evernote.com/api/DeveloperToken.action

EOS

print "Enter the token here: "
token = gets.strip

File.open(File.expand_path("../apitokens/evernote", __FILE__), "w", 0600) do |f|
  f.print(token)
end

puts 'Your developer token was successfully saved to ./apitokens/evernote'
